### ISSUE TITLE
plugin doesn't appear to load

### ISSUE THREAD

**Issue by raesene** [gopher-net/macvlan-docker-plugin#12]
Trying to get the plugin to load, at the moment it doesn't seem to load, no error messages returned...

`uname -a`
`Linux xFoxy 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

`docker -v`
`Docker version 1.10.0, build 590d5108`

`lsmod | grep macvlan`
`macvlan                24576  0`

in the binaries dir
`sudo ./macvlan-docker-plugin-0.3-Linux-x86_64 -d --host-interface=eno16777736 --mode=bridge`

just returns no debug infromation printed...  If I try to create a network I just get
`Error response from daemon: plugin not found`

**Comment by nerdalert** [comment]
Checking that right now. Ping you back shortly.

**Comment by raesene** [comment]
Cool thanks :) Let me know if any additional info. would be helpful!

**Comment by nerdalert** [comment]
Hey @raesene ! I took a look and didn't see any issues but I updated the binary and added a link to a gist the has verbose output [here](https://gist.github.com/nerdalert/37c251dd262eb55d616c).

More I think about it, I think you maybe have an old plugin revision maybe. The location of the `.sock` file changed last year could it be possible you have a docker service from an old package install running? Im sure its unlikely but thats the only thing I can think of since docker and the plugin both default to `/var/run/docker/plugins` and I think the plugin creates the path if it doesn't exist if I remember correctly.

After you start the plugin a file named `macvlan.sock` should be created.

```
$ ls -l /var/run/docker/plugins/
total 0
0 srwxr-xr-x 1 root root 0 Feb  7 15:16 macvlan.sock
```

-One other thing it looks like you are sending `--host-interface=` and `--mode` via the plugin as parameters. We now send generic key/value options via the network create `-o` or `--options` so it is all native with `docker network` commands and the only macvlan supported mode is `bridge` so it is by default.

Refresh the latest plugin binary I just pushed also if you don't mind to make sure you are on the latest commit.

Could you shoot me the output of the plugin from this?

```
# Start Docker
$ docker daemon

# Start the plugin (-d == debug) no parameters required. Options will be passed via docker network create
$ sudo ./macvlan-docker-plugin-0.3-Linux-x86_64 -d

# Create a network (-d macvlan) tells the driver to look for the file handle macvlan.sock in the /var/run/docker/plugins directory.
$ docker network create -d macvlan -o host_iface=eno16777736 -o --subnet=<subnet on eno16777736 x.x.x.x/y> mcv-net

# Run a container
$ docker run --net=mcv-net -it --rm busybox
```
- Here is a [video](https://www.youtube.com/watch?v=IMOelqPzFtk&spfreload=10) with the commands and example also if it helps.

Thanks!

**Comment by raesene** [comment]
Hi @nerdalert 

Cool that works fine now, gettting the debug info on the plugin and the socket is showing up :)

The only thing I noticed now when running those is commands is that by default when I start the container it'll assign the lowest available IP address in the subnet to the container (e.g. on 192.168.41.0/24 when I create the container I get 192.168.41.2) and I didn't see an option to tell the container to just use the host network's DHCP server, although it's possible to just pass --ip on container setup and use a static IP, wich works fine.

**Comment by nerdalert** [comment]
Awesome! So great points 
- On `--ip` that is a new v1.10 feature. I'm glad you pointed that out. Need to add it to the README. Something like:

```
$ docker run --ip=172.16.86.10 --net=mcv-eth0 -it --rm busybox
```
- Regarding DHCP, I have heard mention of a proxy/helper to send the broadcast. I go back and forth on the latency added with a DHCP bcast/lookup/unicast reply and its affect on the time scale of people expecting < 1 second container run times. Will poke around and ping you if I see something or write something with the IPAM plugin. 

Appreciate the feedback, going to close this out. Thanks!
