### ISSUE TITLE
Error: driver modified interface address

### ISSUE THREAD

**Issue by hustcat** [gopher-net/macvlan-docker-plugin#18]
When I start container, I got some errors:

```
#docker network create -d macvlan --subnet=192.168.1.0/24 --gateway=192.168.1.1 -o host_iface=eth0 macvlan1

# docker run --net=macvlan1 -itd  --name='vm1-1' sshd:1.0
2425bab3b130484ed7325a2867c3c03dceae5882b2a3557d6392dcdfa62745a2
docker: Error response from daemon: failed to create endpoint vm1-1 on network macvlan1: driver modified interface address: endpoint interface IP present (192.168.1.2/24). Cannot be modified with (192.168.1.2/24).; failed to roll back: NetworkDriver.DeleteEndpoint: The requested interface to delete [ 20fff ] was not found on the host..
```

docker version:

```
# docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 20:39:58 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 20:39:58 2016
 OS/Arch:      linux/amd64
```

From [here](https://github.com/docker/libnetwork/blob/master/endpoint_info.go#L243), it seems that libnetwork should check whether address is same.

**Comment by nerdalert** [comment]
Hey @hustcat ! We are adding macvlan/ipvlan support natively, so there is no need to run a separate daemon like with this repo's 3rd party remote driver process, it will be included with the Docker binary inside of Libnetwork. The patch is still under review and not merged yet. If you want to give it a go, you can either build it from the PR listed in these notes [Macvlan, Ipvlan and 802.1q Trunk Native Docker Support Notes](https://gist.github.com/nerdalert/c0363c15d20986633fda)

Your point on the address is great. If you create a network with a subnet and then try to explicitly run a container with `--ip=x.x.x.x` that does not match the network's subnet will get rejected. In the case of the Macvlan driver we will not check eth0 to see if the `network create --subnet=` matches since having an IP address on `eth0` isn't required and in some cases having an isolated network may be useful.
- To do your example, give the following a run:
1. Download the Docker experimental binary found at the top of the page at: [Macvlan, Ipvlan and 802.1q Trunk Native Docker Support Notes](https://gist.github.com/nerdalert/c0363c15d20986633fda)

```
wget <link to binary from notes.zip>
unzip docker-1.11.0-dev.zip
# -D is optional debug if you want some debug details
./docker-1.11.0-dev daemon -D 
```
1. In a new window, create the MacVlan Network with:

```
docker network create -d macvlan --subnet=192.168.1.0/24 --gateway=192.168.1.1 -o host_iface=eth0 macvlan1
```
1. Run the container and exec into the container:

```
docker run --net=macvlan1 -itd  --name=vm1-1 debian
# docker ps and get the CID
docker exec -it 9e2f0fa336ea /bin/sh
```

Here is all of the output if it helps (note, the sshd image you specified didn't resolve for me so I just spun up debian. If you haven't used `docker exec` to spawn a container shell and connect to it its super handy):

```
$ docker network create -d macvlan --subnet=192.168.1.0/24 --gateway=192.168.1.1 -o host_iface=eth0 macvlan1
7f57c9982b743e6417e8fe1109c07550f4b9244c035e93e0a102f2bebb7c8651

$ docker run --net=macvlan1 -itd  --name=vm1-1 debian
3b4ff40124f6d81516f4e4c18627b15be219382968d01a0fa23aa2b23cb7807d

$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
3b4ff40124f6        debian              "/bin/bash"         10 seconds ago      Up 10 seconds                           vm1-1

$ docker exec -it 3b4ff40124f6 /bin/sh
#
# ip a show eth0
102: eth0@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default
    link/ether 96:1b:be:c0:2c:af brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.2/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::941b:beff:fec0:2caf/64 scope link
       valid_lft forever preferred_lft forever

# ip route
default via 192.168.1.1 dev eth0
192.168.1.0/24 dev eth0  proto kernel  scope link  src 192.168.1.2
```

Thanks a bunch for testing it out and please let me know if you have any issues!

**Comment by hustcat** [comment]
@nerdalert I have done some changes to make it run success. It's a great job, thank you.

**Comment by nerdalert** [comment]
Thanks @hustcat ! Love any feedback on the native driver. 

If you test it out and have any issues or use cases it doesn't solve don't hesitate to ping. [Macvlan, Ipvlan and 802.1q Trunk Driver Notes](https://gist.github.com/nerdalert/c0363c15d20986633fda#getting-started) 
Thanks!
